# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-27 14:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='date',
            new_name='create_date',
        ),
        migrations.AlterField(
            model_name='session',
            name='date_expired',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 4, 14, 5, 40, 377922)),
        ),
    ]
