# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-27 16:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_auto_20170927_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.Comment'),
        ),
        migrations.AlterField(
            model_name='session',
            name='date_expired',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 4, 16, 51, 19, 347945)),
        ),
    ]
